# Generated by SQL Server Management Studio at 3:35 PM on 8/31/2017

Import-Module SqlServer
# Set up connection and database SMO objects

$sqlConnectionString = "Data Source=JSZHT-DESKTOP;Initial Catalog=ZZU-DB;Integrated Security=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True;Packet Size=4096;Application Name=`"Microsoft SQL Server Management Studio`";Column Encryption Setting=Enabled"
$smoDatabase = Get-SqlDatabase -ConnectionString $sqlConnectionString

# If your encryption changes involve keys in Azure Key Vault, uncomment one of the lines below in order to authenticate:
#   * Prompt for a username and password:
#Add-SqlAzureAuthenticationContext -Interactive

#   * Enter a Client ID, Secret, and Tenant ID:
#Add-SqlAzureAuthenticationContext -ClientID '<Client ID>' -Secret '<Secret>' -Tenant '<Tenant ID>'

# Change encryption schema

$encryptionChanges = @()

# Add changes for table [dbo].[Student]
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.Student.IDNumber -EncryptionType Deterministic -EncryptionKey "CEK_Auto1"

Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase

